# Generated by Django 3.2.9 on 2021-11-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='totalPoint',
            field=models.IntegerField(default=0),
        ),
    ]
