# Generated by Django 3.2.9 on 2021-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
