# Generated by Django 3.2.9 on 2021-11-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='totalPoint',
            new_name='total_point',
        ),
    ]
