# Generated by Django 3.2.9 on 2021-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_title',
            field=models.TextField(default=''),
        ),
    ]
