# Generated by Django 3.2.9 on 2021-11-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0002_problem_problem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='path_to_test_file',
            field=models.FileField(upload_to=''),
        ),
    ]
