# Generated by Django 3.2.9 on 2021-11-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0004_problem_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='limit_memory',
            new_name='memory_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='limit_time',
            new_name='time_limit',
        ),
    ]
