# Generated by Django 3.2.9 on 2021-11-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0005_auto_20211122_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_score',
            new_name='user_point',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_score',
            new_name='user_point',
        ),
    ]
