# Generated by Django 3.2.9 on 2021-11-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0006_auto_20211122_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name_in_themis',
            field=models.TextField(default=''),
        ),
    ]
