# Generated by Django 3.2.9 on 2021-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0009_auto_20211124_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_point',
            field=models.TextField(default=''),
        ),
    ]
